### ISSUE TITLE
Issues on homepage shown on mobile devices

### ISSUE THREAD

**Issue by wiven** [wivenwebsolutions/RestaurantAtHome#1]
@Baggeraar could you fix the following issues on the homepage?
- in file.css on line 137 could you delete the _"min-width"_-element? This is causing some issues on mobile devices (as such iPhone etc.)
- The button with class _"navbar-toggle collapsed"_ does not show anything, but causes the logo to be pushed down

**Comment by Baggeraar** [comment]
Can you specify the correct css file?
Mentioned button has been deleted; was a button for testing purposes which slipped past the removal process.

**Comment by wiven** [comment]
My bad. The bug in in file _screen.css_, on line 137 as mentioned before.

**Comment by Baggeraar** [comment]
should be fixed now. Can you please verfify?
