### ISSUE TITLE
Active tab on 'slotedit' page

### ISSUE THREAD

**Issue by wiven** [wivenwebsolutions/RestaurantAtHome#10]
The active tab on the slotedit page does not work. As you can see here https://www.dropbox.com/s/5js3yi0cmqyc7d0/Schermafdruk%202015-05-17%2018.04.53.png?dl=0. The active tab is "Mijn gerechten".

**Comment by Baggeraar** [comment]
It's not a bug, it's a feature.
The side menu is a seperate template so it cant be changed for the different pages for now. We will have to do that via php.
We can mock up a javascript that does this but this will take some time all for nothing, because we will need to do this properly with php.

**Comment by wiven** [comment]
Fair enough, was just pointing out. Can be done with jQuery too if I'm not mistaking. I'll leave it up to you ;-)
