### ISSUE TITLE
Scaling issue on homepage carousel

### ISSUE THREAD

**Issue by Baggeraar** [wivenwebsolutions/RestaurantAtHome#2]
There is a scaling issue with the images shown in the background carousel.
It's a bit of a mindbreaker that one, so that scaling issue might take some time. feel free to propose a solution.

**Comment by wiven** [comment]
For the background pictures there has been made a collaboration between RestaurantAtHome and [Tafel27.be](http://tafel27.be). Pictures of the site (in highres) can be put in the slider for free in return for a link back in the disclaimer.

**Comment by Baggeraar** [comment]
fixed I guess...
