### ISSUE TITLE
Footer on all pages

### ISSUE THREAD

**Issue by wiven** [wivenwebsolutions/RestaurantAtHome#3]
Footer on all pages does not stick to the bottom. A fix should be found to that, especially on the admin-section.

**Comment by wiven** [comment]
Found the problem causing the footer not to stick to the bottom.
In file "screen.css" on line 113 `#wrap` has a padding of `0 0 60px;`.

**Comment by Baggeraar** [comment]
Thats actually by design.
the -60px is so the footer doesn't make the page longer than it should be.

The implementation on the homepage is actually correct i think, it should just be implemented into the other pages.

**Comment by wiven** [comment]
Solved by commit cb580bce8b77b474edf48c6e26009a14a10f9668. Can be closed.
