### ISSUE TITLE
Input fields on slotedit page

### ISSUE THREAD

**Issue by wiven** [wivenwebsolutions/RestaurantAtHome#4]
On the slotedit page the field `Datum` is more to the right than the button underneath. Isn't it possible to give it a width of 100% in it's parent div? And the readonly attribute gives it a grey overlay. Can this be disabled with adding some CSS (`cursor: default; background-color: #fff;`)?

**Comment by Baggeraar** [comment]
Should be fixed.

**Comment by wiven** [comment]
Can this be added to all the inputfields with a help pop-up?
