### ISSUE TITLE
Base_url

### ISSUE THREAD

**Issue by Baggeraar** [wivenwebsolutions/RestaurantAtHome#5]
base_url() = restaurantathome.be
public_url() = restaurantathome.be/public

please do not use base_url for images because it does not work.
the favicons for example do not work.

**Comment by wiven** [comment]
Favicons do work as they're not in the public folder. @Baggeraar could you give an example of a favicon not working? FYI `base_url()` for images has been changed to `public_url()`, you're absolutely right on that one.

**Comment by wiven** [comment]
Fixed by commit 325ad8e5ce60d6f68ae25ba426b83838a9bdf8c6.
