### ISSUE TITLE
Home - "Where to Eat" is very small (At Playground)

### ISSUE THREAD

**Issue by thdepauw** [wivenwebsolutions/RestaurantAtHome#66]
![image](https://cloud.githubusercontent.com/assets/6310466/10287192/fa55b430-6b91-11e5-91c8-731ca18caeef.png)

**Comment by thdepauw** [comment]
Vlam, gwn copy past rechtstreeks in git ... nice

**Comment by FreDeRoover** [comment]
We zijner nog aan bezig ;)
