### ISSUE TITLE
Left hand side of slot edit page

### ISSUE THREAD

**Issue by wiven** [wivenwebsolutions/RestaurantAtHome#9]
@Baggeraar wouldn't it be better to align the date input field and the button `Standaard weekschema aanpassen` to the left side? Practically seen: date input field with `width` 100%. Feel free to share your opinion on this one.

**Comment by Baggeraar** [comment]
like this?
http://i.imgur.com/aKOevlr.jpg

**Comment by wiven** [comment]
Hmm, I wouldn't exactly make it wider. As the adminsection will be managed on tablets (hence the smaller screen). What's the result of keeping the same width and aligning it left (and `width` of 100%)?
